export const events = [
  {
    id: "1",
    title: "Next.js Conference",
    description: "Learn all about Next.js and the future of web development.",
    date: "2025-09-10",
    location: "Dhaka",
    category: "Conference",
  },
  {
    id: "2",
    title: "React Workshop",
    description: "Hands-on workshop with React for beginners and pros.",
    date: "2025-09-15",
    location: "Chittagong",
    category: "Workshop",
  },
  {
    id: "3",
    title: "Startup Pitch Night",
    description: "Local startups pitch their ideas to investors and mentors.",
    date: "2025-09-20",
    location: "Dhaka",
    category: "Networking",
  },
  {
    id: "4",
    title: "AI & Machine Learning Summit",
    description: "Experts discuss the latest trends in AI and ML applications.",
    date: "2025-10-05",
    location: "Sylhet",
    category: "Conference",
  },
  {
    id: "5",
    title: "Women in Tech Meetup",
    description: "An empowering meetup for women working in technology.",
    date: "2025-10-12",
    location: "Khulna",
    category: "Meetup",
  },
  {
    id: "6",
    title: "Cloud Computing Bootcamp",
    description: "Intensive 2-day bootcamp on AWS, Azure, and GCP.",
    date: "2025-10-18",
    location: "Dhaka",
    category: "Workshop",
  },
  {
    id: "7",
    title: "UI/UX Design Conference",
    description: "Designers share insights on modern UI/UX practices.",
    date: "2025-10-25",
    location: "Rajshahi",
    category: "Conference",
  },
  {
    id: "8",
    title: "Tech Career Fair",
    description: "Meet top companies and recruiters in the tech industry.",
    date: "2025-11-02",
    location: "Dhaka",
    category: "Career",
  },
  {
    id: "9",
    title: "Blockchain Hackathon",
    description: "48-hour hackathon focused on blockchain innovations.",
    date: "2025-11-08",
    location: "Chittagong",
    category: "Hackathon",
  },
  {
    id: "10",
    title: "Digital Marketing Summit",
    description: "Learn the latest digital marketing strategies from experts.",
    date: "2025-11-15",
    location: "Barisal",
    category: "Conference",
  },
];
